INSERT INTO question (created_at, modified_at, question) VALUES
(NOW(), NOW(), '새로운 프로젝트에 착수합니다. 팀원들이 다양한 아이디어를 내놓습니다. 당신은?'),
(NOW(), NOW(), '개발을 할 장소를 선택할 수 있다면, 어디서 하시겠습니까?'),
(NOW(), NOW(), '프로젝트 중간에 시스템 문제가 생겼습니다. 어떻게 대응하시겠습니까?'),
(NOW(), NOW(), '새로운 프로그래밍 언어를 배우려 합니다. 어떻게 시작하시겠습니까?'),
(NOW(), NOW(), '오랜만에 개발 환경을 세팅합니다. 어떻게 접근하시겠습니까?'),
(NOW(), NOW(), '프로젝트를 기획할 때, 어떤 접근 방식을 선호합니까?'),
(NOW(), NOW(), '팀원과의 의견 차이로 갈등이 생겼습니다. 어떻게 해결하시겠습니까?'),
(NOW(), NOW(), '중요한 결정을 내릴 때, 어떤 기준을 주로 고려하십니까?'),
(NOW(), NOW(), '프로젝트의 성공 여부를 평가할 때, 무엇을 중점적으로 보십니까?'),
(NOW(), NOW(), '프로젝트의 타임라인을 관리할 때, 어떤 방식을 선호하십니까?'),
(NOW(), NOW(), '프로젝트 중 중요한 결정을 내릴 때, 어떤 절차를 따르십니까?'),
(NOW(), NOW(), '프로젝트 도중 예상치 못한 변경 사항이 생겼습니다. 어떻게 대처하시겠습니까?');

INSERT INTO option (score, question_id, answer, personality_type) VALUES
(1, 1, '모두 모여 브레인스토밍! 다양한 의견 환영!', 'EXTROVERSION'),
(1, 1, '깊이 생각해본 후 의견을 정리해서 제안.', 'INTROVERSION'),
(1, 2, '시끌벅적한 카페나 오픈 오피스, 활기찬 곳에서!', 'EXTROVERSION'),
(1, 2, '조용한 홈 오피스, 완전히 집중할 수 있는 곳!', 'INTROVERSION'),
(1, 3, '동료들에게 물어보거나 온라인 포럼에 도움 요청!', 'EXTROVERSION'),
(1, 3, '차분히 문제 원인을 분석하고 스스로 해결책을 찾는다.', 'INTROVERSION'),
(1, 4, '코딩 예제부터 따라하면서 직접 해본다.', 'SENSING'),
(1, 4, '이론과 개념을 먼저 공부하고 나서 시작한다.', 'INTUITION'),
(1, 5, '예전에 쓰던 설정을 그대로 사용한다.', 'SENSING'),
(1, 5, '최신 버전과 새로운 도구를 시도해본다.', 'INTUITION'),
(1, 6, '이전에 성공했던 방법을 참고하여 기획한다.', 'SENSING'),
(1, 6, '새로운 아이디어와 창의적인 접근 방식을 고려한다.', 'INTUITION'),
(1, 7, '머리로 분석해서 해결합니다.', 'THINKING'),
(1, 7, '마음을 열어서 대화하며 해결합니다.', 'FEELING'),
(1, 8, '데이터와 사실을 중요시합니다.', 'THINKING'),
(1, 8, '팀원들의 감정과 관계를 중시합니다.', 'FEELING'),
(1, 9, '목표 달성과 성과 지표를 중시합니다.', 'THINKING'),
(1, 9, '팀원들의 만족도와 협업을 중요시합니다.', 'FEELING'),
(1, 10, '계획을 엄격하게 따르는 편입니다.', 'JUDGING'),
(1, 10, '상황에 따라 유연하게 조정하는 편입니다.', 'PERCEIVING'),
(1, 11, '빠르게 결정하고 실행에 옮깁니다.', 'JUDGING'),
(1, 11, '여러 가지 옵션을 고려하며 천천히 결정합니다.', 'PERCEIVING'),
(1, 12, '계획을 유연하게 수정합니다.', 'JUDGING'),
(1, 12, '상황에 따라 적응하여 대처합니다.', 'PERCEIVING');

INSERT INTO image (original_file_name, store_file_name, url) VALUES
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg'),
('karina.jpg', 'd290f1ee-6c54-4b01-90e6-d701748f0851.jpg', 'https://webti-imagebucket.s3.eu-north-1.amazonaws.com/karina.jpg');

INSERT INTO web_developer_profile (created_at, modified_at, description, mbti_type, result, image_id) VALUES
(NOW(), NOW(), '데이터의 정확성과 안정성을 최우선으로 하는 당신은 백엔드 개발의 수호자! 체계적이고 신뢰할 수 있는 방식으로 데이터를 관리하며, 버그는 당신에게 있어 전설 속 이야기일 뿐입니다. 당신의 코드는 그야말로 철옹성!', 'ISTJ', '철저한 데이터 관리형 백엔드 개발자', 1),
(NOW(), NOW(), '소프트웨어 개발의 체스 그랜드마스터인 당신은, 몇 수 앞을 내다보는 전략가! 시스템 아키텍처를 전략적으로 설계하고, 최적의 경로를 찾아내는 당신의 코드는 예술 작품과 같습니다. 복잡한 문제도 순식간에 해결하는 능력자!', 'INTJ', '전략적 시스템 설계형 백엔드 개발자', 2),
(NOW(), NOW(), '프로그래밍 세계의 맥가이버, 당신! 실용적이고 논리적인 사고로 문제를 해결하며, 시스템 최적화와 효율적인 코드 작성에 탁월한 재능을 보입니다. 종이 클립 하나로도 문제를 해결할 수 있을 것 같은 당신의 능력은 그야말로 경이롭습니다.', 'ISTP', '효율적인 문제 해결형 백엔드 개발자', 3),
(NOW(), NOW(), '코드의 아인슈타인인 당신은, 복잡한 알고리즘과 데이터 구조 설계에서 빛을 발합니다. 끊임없이 새로운 아이디어가 떠오르는 당신의 머릿속은 혁신으로 가득 차 있으며, 논리적이고 분석적인 사고로 누구도 해결하지 못하는 문제를 해결합니다.', 'INTP', '혁신적인 알고리즘 전문가 백엔드 개발자', 4),
(NOW(), NOW(), '사용자의 마음을 읽는 텔레파시 능력을 가진 당신은 UI/UX 디자인의 귀재! 세심하고 헌신적으로 사용자 경험을 중시하며, 직감적으로 사용자가 원하는 인터페이스를 설계합니다. 당신의 작업물은 언제나 사용자의 기대를 넘어서죠!', 'ISFJ', '섬세한 사용자 경험 디자이너형 프론트엔드 개발자', 5),
(NOW(), NOW(), '프론트엔드 세계의 예술가인 당신은 사교적이고 에너제틱하며, 사용자와의 상호작용을 즐깁니다. 반응형 웹 디자인에 강점을 발휘하며, 당신의 작업물은 언제나 화려하고 눈길을 사로잡습니다. 당신의 웹 페이지는 마치 예술 작품과 같습니다!', 'ESFP', '창의적인 인터페이스 디자이너형 프론트엔드 개발자', 6),
(NOW(), NOW(), '창의성과 열정의 화신인 당신은 새로운 아이디어와 혁신적인 디자인으로 사용자 경험을 극대화합니다. 사람들과의 상호작용을 즐기며, 당신의 작업은 언제나 신선하고 놀라운 요소들로 가득합니다. 당신의 웹사이트 탐험은 마치 모험과도 같죠!', 'ENFP', '혁신적인 UX/UI 전문가형 프론트엔드 개발자', 7),
(NOW(), NOW(), '사용자 중심의 접근 방식을 중시하는 당신은 사용자 인터페이스 디자인과 고객 요구 사항 반영에 탁월한 능력을 보입니다. 사용자가 원하는 모든 것을 제공하며 편안함을 줍니다. 당신의 작업물은 언제나 사용자에게 편안함을 줍니다!', 'ESFJ', '사용자 중심 인터페이스 개발자형 프론트엔드 개발자', 8),
(NOW(), NOW(), '창의적이고 통찰력 있는 당신은 전체적인 비전을 가지고 프로젝트를 추진합니다. 백엔드와 프론트엔드를 모두 이해하며, 사용자와 시스템 간의 조화를 고려하는 능력을 지니고 있습니다. 당신의 프로젝트는 시처럼 아름답게 완성됩니다!', 'INFJ', '전체 비전을 갖춘 개발자형 풀스택 개발자', 9),
(NOW(), NOW(), '새로운 기술을 빠르게 습득하고 다양한 문제를 해결할 수 있는 당신은 프로그래밍의 만능 해결사! 혁신적인 접근 방식과 도전 정신으로 프로젝트를 성공적으로 이끕니다. 당신의 프로젝트는 항상 혁신적입니다!', 'ENTP', '다양한 기술을 아우르는 문제 해결사형 풀스택 개발자', 10),
(NOW(), NOW(), '팀의 리더이자 조정자인 당신은 카리스마 있고 협력적이며, 사람들을 이끄는 능력이 뛰어납니다. 팀의 비전을 공유하고 협력하여 목표를 달성하는 데 주력합니다. 당신이 이끄는 프로젝트는 언제나 성공적입니다!', 'ENFJ', '협력과 조정을 이끄는 개발자형 풀스택 개발자', 11),
(NOW(), NOW(), '전략적이고 리더십이 뛰어난 당신은 장기적인 목표와 전략을 세워 프로젝트를 이끌며, 논리적이고 효율적인 접근 방식을 사용합니다. 프로젝트를 마치 군대처럼 철저히 계획하고 성공적으로 수행합니다. 당신의 프로젝트는 항상 성공적입니다!', 'ENTJ', '전략적 프로젝트 리더형 풀스택 개발자', 12),
(NOW(), NOW(), '당신은 체계적이고 조직적인 접근 방식을 통해 백엔드 시스템을 효율적으로 관리합니다. 철저한 계획과 규칙을 중시하며, 팀을 이끌어 프로젝트를 성공적으로 완수합니다. 당신의 코드는 언제나 깔끔하고 명확하며, 시스템의 신뢰성을 보장합니다.', 'ESTJ', '실행력 강한 관리자형 백엔드 개발자', 13),
(NOW(), NOW(), '당신은 섬세하고 창의적인 디자인 감각으로 사용자 인터페이스를 아름답게 구현합니다. 세밀한 부분까지 놓치지 않으며, 사용자가 시각적으로 즐길 수 있는 웹사이트를 만듭니다. 당신의 작업물은 예술 작품처럼 정교하고 매력적입니다.', 'ISFP', '디테일에 강한 시각 예술가형 프론트엔드 개발자', 14),
(NOW(), NOW(), '사용자 경험에 깊은 공감을 가지고 디자인하는 당신은, 감성적이고 창의적인 방식으로 웹 페이지를 만듭니다. 사용자와의 상호작용에서 진정성을 발휘하며, 웹사이트를 통해 따뜻한 이야기를 전합니다. 당신의 작업물은 사용자의 마음을 움직입니다.', 'INFP', '공감하는 이야기꾼형 프론트엔드 개발자', 15),
(NOW(), NOW(), '당신은 변화와 도전에 강하며, 문제를 해결하는 데 있어 유연하고 즉흥적인 접근 방식을 취합니다. 실용적이고 효율적인 방법을 선호하며, 빠른 결단력으로 프로젝트를 성공적으로 이끌어갑니다. 당신의 작업은 항상 실용적이고 동적입니다.', 'ESTP', '유연하고 즉흥적인 개발자형 풀스택 개발자', 16);

INSERT INTO statistic (created_at, modified_at, developer_profile_id, count, match_count) VALUES
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ISTJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'INTJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ISTP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'INTP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ESTJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ISFJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ESFP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ENFP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ISFP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'INFP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ESFJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'INFJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ENTP'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ENFJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ENTJ'), 0, 0),
(NOW(), NOW(), (SELECT id FROM web_developer_profile WHERE mbti_type = 'ESTP'), 0, 0);
