FROM docker.elastic.co/beats/filebeat:8.14.0

USER root

COPY filebeat.yml /usr/share/filebeat/filebeat.yml

RUN groupadd -f docker
RUN usermod -aG docker filebeat

RUN chown filebeat:filebeat /usr/share/filebeat/filebeat.yml

RUN chmod 640 /usr/share/filebeat/filebeat.yml

USER filebeat
